name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    quality:
        name: Quality Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun install

            - name: Lint
              run: bun run lint

            - name: Build
              run: bun run build

            - name: Verify Build Artifacts
              run: bun run test:dist

            - name: Test
              run: bun run test

            - name: Benchmark
              run: bun run benchmark
